### ISSUE TITLE
Error running standalone planner

### ISSUE THREAD

**Issue by debloper** [fabric8-ui/fabric8-planner#1991]
Following is the last bit of stdout where the error happens:

```
> fabric8-planner-runtime@0.0.1 start /home/deb/dev/fabric8/planner/runtime
> npm run server:dev


> fabric8-planner-runtime@0.0.1 server:dev /home/deb/dev/fabric8/planner/runtime
> webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/

module.js:471
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/webpack-dev-server/lib/Server.js:15:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 4.11.3-200.fc25.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "server:dev"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! fabric8-planner-runtime@0.0.1 server:dev: `webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fabric8-planner-runtime@0.0.1 server:dev script 'webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fabric8-planner-runtime package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fabric8-planner-runtime
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fabric8-planner-runtime
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/deb/dev/fabric8/planner/runtime/npm-debug.log

npm ERR! Linux 4.11.3-200.fc25.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! fabric8-planner-runtime@0.0.1 start: `npm run server:dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fabric8-planner-runtime@0.0.1 start script 'npm run server:dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fabric8-planner-runtime package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run server:dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fabric8-planner-runtime
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fabric8-planner-runtime
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/deb/dev/fabric8/planner/runtime/npm-debug.log
```

**Comment by debloper** [comment]
Global installation of `webpack` fixes this problem.
