### ISSUE TITLE
Library build's watch mode breaks on branch-switch

### ISSUE THREAD

**Issue by debloper** [fabric8-ui/fabric8-planner#2438]
This is because of the fact that on branch switch, the `gulpfile` is replaced with older gulpfile and the `watch` routine isn't the same anymore.

This is easily fixed by fetching the latest master's changes into the working branches (so that the gulpfiles are same across branches). After which this problem won't happen anymore.

To solve this programmatically, we'll have to add a git hook that overwrites Gulpfiles on branch changes, as temporary solution, until everyone has checked out the new code to their working branch. After which, this will again have to be removed.

**Comment by nimishamukherjee** [comment]
@debloper how was this working before?
Also, code changes breaks the build's watch mode.

**Comment by nimishamukherjee** [comment]
This happens on a new branch which is up to date with master (has the new gulp file). Build mode breaks when I make code changes.

/home/nimisha/Desktop/GIT/almighty-ui/gulpfile.js:123
      mach.transpileTS();
           ^
TypeError: mach.transpileTS is not a function
    at FSWatcher.<anonymous> (/home/nimisha/Desktop/GIT/almighty-ui/gulpfile.js:123:12)
    at emitTwo (events.js:126:13)
    at FSWatcher.emit (events.js:214:7)
    at FSWatcher.<anonymous> (/home/nimisha/Desktop/GIT/almighty-ui/node_modules/gulp/node_modules/chokidar/index.js:198:15)
    at FSWatcher._emit (/home/nimisha/Desktop/GIT/almighty-ui/node_modules/gulp/node_modules/chokidar/index.js:240:5)
    at FSWatcher.<anonymous> (/home/nimisha/Desktop/GIT/almighty-ui/node_modules/gulp/node_modules/chokidar/lib/nodefs-handler.js:263:16)
    at FSReqWrap.oncomplete (fs.js:153:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fabric8-planner@0.0.0-development build: `gulp build "--watch"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fabric8-planner@0.0.0-development build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-15T09_13_01_498Z-debug.log
